const LABEL_CONSTANTS = {
  REGISTRATION: {
    COMPANY_NAME: 'Company Name',
    ALIAS: 'Alias',
    CONTACT_NAME: 'Contact Name',
    CONTACT_EMAIL: 'Contact Email',
    CONTACT_PHONE: 'Contact Phone',
    REGISTRATION_BTN: 'Register',
    REGISTRATION_TITLE: 'REGISTRATION',
    LOGIN_BTN: 'Login',
    LOGIN_TITLE: 'LOGIN',
    PASSWORD: 'Password',
  },
  MENUITEMS: {
    HOME: 'HOME',
    ORGANIZATION: 'ORGANIZATION',
    PROFILE: 'PROFILE',
    BRANCH: 'BRANCH',
    DEPARTMENT: 'DEPARTMENT',
    DESIGNATION:'DESIGNATION',
    ROLE:'ROLE',
    PERMISSION:'PERMISSION',
    USERMANAGEMNT: 'USER MANAGEMNT',
    USER:'USER',
    GROUP:'GROUP',
    WORKFLOW: 'WORKFLOW',
    MAPPINGS: 'MAPPINGS',
  },
  HOME: {
    HOMETEXT: 'Welcome',
  },
  PROFILE: {
    COMPANY_NAME: 'Company Name',
    TYPE_OF_BUSSINESS: 'Type Of Bussiness',
    ADDRESS1: 'Address 1',
    ADDRESS2: 'Address 2',
    CITY: 'City',
    COUNTRY_STATE: 'County/State',
    COUNTRY: 'Country',
    POSTCODE: 'Postcode',
    TAX: 'TAX',
    INDUSTRY: 'Industry Vertical',
    CONTACT_NAME: 'Contact Name',
    EMAIL_1: 'Email 1',
    EMAIL_2: 'Email 2',
    DESIGNATION: 'Designation',
    PHONE_1: 'Phone 1',
    PHONE_2: 'Phone 2',
    TAB_LEGAL: 'LEGAL',
    TAB_CONTACT: 'CONTACT',
    TAB_BTN: 'Edit/Save',
    ADD_NEW: 'Add New',
  },
  BRANCH: {
    BRANCH_NAME: 'Branch Name',
    TYPE_OF_BUSSINESS: 'Type Of Bussiness',
    ADDRESS1: 'Address 1',
    ADDRESS2: 'Address 2',
    CITY: 'City',
    COUNTRY_STATE: 'County/State',
    COUNTRY: 'Country',
    POSTCODE: 'Postcode',
    TAX: 'TAX',
    INDUSTRY: 'Industry Vertical',
    CONTACT_NAME: 'Contact Name',
    EMAIL_1: 'Email 1',
    EMAIL_2: 'Email 2',
    DESIGNATION: 'Designation',
    PHONE_1: 'Phone 1',
    PHONE_2: 'Phone 2',
    TAB_LEGAL: 'LEGAL',
    TAB_CONTACT: 'CONTACT',
    TAB_BTN: 'Edit/Save',
    ADD_NEW: 'Add New',
  },
  DEPARTMENT: {
    DEPARTMENT_NAME: 'Department Name',
    BRANCH: 'Branch',
    PARENTDEP: 'Parent Department',
    DEPARTMENT_CODE: 'Department Code',
    DESC: 'Description',
    STATUS: 'Status',
    TAB_BTN: 'Edit/Save',
    ADD_NEW: 'Add New',
    ACTION:"Action"
  },
  DESIGNATION: {
    DESIGNATION_NAME: 'Designation Name',
    DEPARTMENT: 'Department',
    DESIGNATION_CODE: 'Designation Code',
    DESC: 'Description',
    STATUS: 'Status',
    TAB_BTN: 'Edit/Save',
    ADD_NEW: 'Add New',
    ACTION:"Action"
  },
  ROLE: {
    ROLE_NAME: 'Role Name',
    ROLE_CODE: 'Role Code',
    DESC: 'Description',
    STATUS: 'Status',
    TAB_BTN: 'Edit/Save',
    ADD_NEW: 'Add New',
    ACTION:"Action"
  },
  PERMISSION: {
    PERMISSION_NAME: 'Permission Name',
    DESC: 'Description',
    STATUS: 'Status',
    TAB_BTN: 'Edit/Save',
    ADD_NEW: 'Add New',
    ACTION:"Action"
  },
  USER: {
    USER_NAME: 'User Name',
    USER_EMAIL: 'User Email',
    DEPARTMENT: 'Department',
    DESIGNATION:'Designation',
    ROLE:'Role',
    STATUS: 'Status',
    TAB_BTN: 'Edit/Save',
    ADD_NEW: 'Add New',
    ACTION:"Action"
  },
  GROUP: {
    GROUP_NAME: 'Group Name',
    GROUP_EMAIL: 'Group Email',
    DESC: 'Description',
    USER:'User',
    STATUS: 'Status',
    TAB_BTN: 'Edit/Save',
    ADD_NEW: 'Add New',
    ACTION:"Action"
  },
}
const LABELS = Object.freeze(LABEL_CONSTANTS)

export default LABELS
